apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: s3-sink-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.1.0
  replicas: 1
  bootstrapServers: bitnami-kafka.infra.svc.cluster.local:9092
  # logging:
  #   type: inline
  #   loggers:
  #     connect.root.logger.level: "INFO"
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter.schemas.enable: true
    group.id: s3-sink-connect-cluster
    offset.storage.topic: s3-sink-connect-cluster-offsets
    config.storage.topic: s3-sink-connect-cluster-configs
    status.storage.topic: s3-sink-connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    output:
      type: docker
      image: registry.jingtao.fun/sink-connect-s3:v2  # ensure you can push the image.
    plugins:
      - name: s3-connector
        artifacts:
          - type: zip
            url: https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-s3/versions/10.2.2/confluentinc-kafka-connect-s3-10.2.2.zip
