apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: source-connector-configuration-role
  namespace: infra
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["bitnami-mysql"]
    verbs: ["get"]
