apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-mysql
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: bitnami-mysql-primary.infra.svc.cluster.local
    database.port: 3306
    database.user: root
    database.password: ${secrets:infra/bitnami-mysql:mysql-replication-password}
    database.server.id: 184054
    database.server.name: mysql-test-v3
    database.include.list: db_world
    database.history.kafka.bootstrap.servers: bitnami-kafka.infra.svc.cluster.local:9092
    database.history.kafka.topic: schema-changes.db_world
