metrics:
  enabled: true
  serviceMonitor:
    enabled: true # Create ServiceMonitor Resource for scraping metrics using PrometheusOperator
    namespace: infra
    honorLabels: true
    interval: 5s

persistence:
  enabled: true
  storageClass: standard
  size: 100Gi

replicaCount: 2

zookeeper:
  enabled: true
  replicaCount: 2
  auth:
    client:
      enabled: false
  persistence:
    storageClass: standard