global:
  imageRegistry: docker.io.registry.jingtao.fun
  storageClass: standard
  
singleuser:
  persistence:
    storageClass: standard

hub:
  password: jupyter

postgresql:
  enabled: true

externalDatabase:
  host: bitnami-postgresql-primary.infra.svc.cluster.local
  user: jupytertest
  password: nopasswd
  database: jupyterhub
