global:
  imageRegistry: docker.io.registry.jingtao.fun
  storageClass: standard

persistence:
  enabled: true
  storageClass: standard

auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext

replicaCount: 3

metrics:
  kafka:
    enabled: true

provisioning:
  enabled: true
  numPartitions: 2

zookeeper:
  enabled: true
  replicaCount: 3
  auth:
    client:
      enabled: false
  persistence:
    storageClass: standard
