global:
  imageRegistry: docker.io.registry.jingtao.fun
prometheus:
  persistence:
    enabled: true
    storageClass: standard

  thanos:
    create: true

alertmanager:
  persistence:
    enabled: true
    storageClass: standard