prometheus:
  persistence:
    enabled: true
    storageClass: standard
  replicaCount: 2
  podMonitorNamespaceSelector: # leave empty to select all.
  serviceMonitorNamespaceSelector: # leave empty to select all.
  thanos:
    create: true

operator:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 5s

alertmanager:
  persistence:
    enabled: true
    storageClass: standard
