prometheus:
  persistence:
    enabled: true
    storageClass: standard
  replicaCount: 2
  podMonitorNamespaceSelector: # leave empty to select all.
  serviceMonitorNamespaceSelector: # leave empty to select all.
    

  thanos:
    create: true

operator:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 5s
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics/cluster"
    prometheus.io/port: "9000"

alertmanager:
  persistence:
    enabled: true
    storageClass: standard
