global:
  storageClass: standard

configsvr:
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: standard

mongos:
  replicaCount: 3

shardsvr:
  persistence:
    storageClass: standard
  dataNode:
    replicaCount: 3

metrics:
  enabled: true # Start a side-car prometheus exporter
