global:
  storageClass: standard

configsvr:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: standard

mongos:
  replicaCount: 2

shardsvr:
  persistence:
    storageClass: standard
  dataNode:
    replicaCount: 2

metrics:
  enabled: true # Start a side-car prometheus exporter
  podMonitor:
    enabled: true
    namespace: infra
    interval: 5s
  prometheusRule:
    enabled: true
    namespace: infra
