global:
  imageRegistry: docker.io.registry.jingtao.fun

configsvr:
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: nfs-client

mongos:
  replicaCount: 3

shardsvr:
  persistence:
    storageClass: nfs-client
  dataNode:
    replicaCount: 3

