architecture: replication

global:
  imageRegistry: docker.io.registry.jingtao.fun

# image:
#   tag: 5.7.39-debian-11-r20

primary:
  persistence:
    storageClass: standard

secondary:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: standard
  startupProbe:
    initialDelaySeconds: 30

metrics:
  enabled: true  # Start a side-car prometheus exporter
  image:
    tag: 0.14.0-debian-11-r37
  serviceMonitor:
    enabled: true  # Create ServiceMonitor Resource for scraping metrics using PrometheusOperator
    namespace: infra
    honorLabels: true
    interval: 5s
  prometheusRule:
    enabled: true
    namespace: infra