global:
  storageClass: standard
  postgresql:
    auth:
      postgresPassword: nopasswd
      username: play
      password: nopasswd
      database: jupyterhub

architecture: replication

primary:
  persistence:
    enabled: true
    storageClass: standard

readReplicas:
  replicaCount: 2
  persistence:
    enabled: true
    storageClass: standard

metrics:
  enabled: true # Start a side-car prometheus exporter
  image:
    tag: 0.14.0-debian-11-r37
  serviceMonitor:
    enabled: true # Create ServiceMonitor Resource for scraping metrics using PrometheusOperator
    namespace: infra
    honorLabels: true
    interval: 5s
  prometheusRule:
    enabled: true
    namespace: infra
