global:
  storageClass: standard

metrics:
  enabled: true
  podMonitor:
    enabled: true
    namespace: infra
    interval: 5s
  prometheusRule:
    enabled: true
    namespace: infra

worker:
  replicaCount: 3
