# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: networkd

  ethernets:
    eno1:
      dhcp4: false
      dhcp6: false

  bridges:
    br0:  # This is a virtual bridge. (a three layer switch)
      interfaces:
        - eno1  # This is host physical interface.
      addresses:
        - 192.168.1.90/24  # This is host ip.
      routes:
        - to: default
          via: 192.168.1.41  # This is soft route ip (cannot access external network by ICMP by now.)
      mtu: 1500
      nameservers:
        addresses:
          - 8.8.8.8
          - 192.168.1.41
          - 192.168.1.1
      parameters:
        stp: true
        forward-delay: 4
      dhcp4: no
      dhcp6: no